export const PATH_NAME = {
  LISTVACCINE: "/vaccine-list",
  DETAILVACCINE: "/vaccine/:id",
  REGISTER: "/register",
  LOGIN: "/login",
  BOOKING: "/booking",
  BILL: "/bill",
  PROFILE_CHILD: "/profilechild",
  VACCINATION_SCHEDULE: "/vaccination/:id",
  ABOUT_US: "/aboutus",
  VACCINE_PRICE: "/priceVaccine",
  CAM_NANG: "/camNang",
  BILL_PAYMENT: "/billpayment",
  TRANSACTION: "/transaction",
  VACCINATION_SCHEDULE_STATUS: "/vaccinationScheduleStatus",
  CREATE_CHILD: "/createchild",
  SUCCESS_REGIS: "/successregis",
  SUCCESS_CREATE_PROFILE: "/successbaby",
  SUCCESS_BOOKING: "/successbooking",
  DETAILAPPOIMENT: "/appointmentdetail/:id",

  INJECTION: "/staff/injection-in",
  PROFILE_DOCTOR: "/doctor/profile",
  VACCINE1: "/staff/vaccine",
  VACCINE_DOCTOR: "/doctor/vaccine",
  INJECTION_INFORMATION: "/doctor/injection-in",
  FORGOTPASSWORD: "/forgotpass",
  REPASSWORD: "/repassword",
  IN4: "/in4",
  NEWLIST: "/newlist",
  NEWLDETAIL: "/news/:id",

  DASHBOARD: "/admin/dashboard",
  STAFF: "/admin/staff",
  VACCINE: "/admin/vaccine",
  CHILD: "/admin/child",
  DISEASE: "/admin/disease",
  PAYMENT_HISTORY: "/admin/payment-history",
  PROFILE: "/admin/profile",
};
